library(insuranceData)
data("AutoCollision")
library(ggplot2)
qplot(Severity,Claim_Count,data = AutoCollision,color=Vehicle_Use)
ggplot(AutoCollision,aes(x=Vehicle_Use,y=Claim_Count))+geom_boxplot(fill=c("red","green","blue","pink"))
library(car)
data(Ornstein)
#ggplot(Ornstein,aes(rank))+geom_bar(fill="steelblue4")
#ggplot(Ornstein, aes(rank,fill=discipline))+geom_bar()
ggplot(Ornstein,aes(assets,interlock))+geom_point()
